name: strava-mon
services:
  postgres:
    image: "postgres:14-alpine"
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: strava-mon
      POSTGRES_PASSWORD: strava-mon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strava-mon"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./server/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - '${WEBHOOK_PORT}:${WEBHOOK_PORT}'
    env_file:
      - ./.env
    environment:
      PGHOST: postgres
      PGDATABASE: strava-mon
      PGUSER: strava-mon
      PGPASSWORD: strava-mon
    depends_on:
      postgres:
        condition: service_healthy
  postgrest:
    image: postgrest/postgrest
    ports:
      - '${POSTGREST_PORT}:3000'
    environment:
      PGRST_DB_URI: postgres://strava-mon:strava-mon@postgres:5432/strava-mon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      # TODO: Use a read-only user.
      PGRST_DB_ANON_ROLE: strava-mon
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres-data:
