/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DetailedClubAllOf {
    /**
    * The membership status of the logged-in athlete.
    */
    'membership'?: DetailedClubAllOf.MembershipEnum;
    /**
    * Whether the currently logged-in athlete is an administrator of this club.
    */
    'admin'?: boolean;
    /**
    * Whether the currently logged-in athlete is the owner of this club.
    */
    'owner'?: boolean;
    /**
    * The number of athletes in the club that the logged-in athlete follows.
    */
    'followingCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "membership",
            "baseName": "membership",
            "type": "DetailedClubAllOf.MembershipEnum"
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "boolean"
        },
        {
            "name": "followingCount",
            "baseName": "following_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DetailedClubAllOf.attributeTypeMap;
    }
}

export namespace DetailedClubAllOf {
    export enum MembershipEnum {
        Member = <any> 'member',
        Pending = <any> 'pending'
    }
}
